### ISSUE TITLE
Intrinsic parameters necessary?

### ISSUE THREAD

**Issue by leilai125** [crockwell/rel_pose#1]
Hi, thanks for sharing your work, really appreciate it! I have some questions about intrinsic parameters. Is the camera intrinsic parameters necessary to this algorithm? Can this algorithm work without intrinsic and extrinsic camera parameters? How is the performance (with and without intrinsic parameters)? Because I might have some dataset and want to test, but I have no idea about the intrinsic and extrinsic camera parameters. 

Thank you very much!

**Comment by crockwell** [comment]
Thanks! And, good question! If you are training from scratch, and your intrinsics are consistent across images, it should be fine to just use some reasonable assumption about them (e.g. focal length 128, center 128 for image size of 256x256). I had some early experiments in this case, and it didn't make too much difference to not use intrinsics. 

The time intrinsics are helpful would be if you had intrinsics that vary across images -- that way, it can help the model differentiate difference in camera vs. difference in relative pose.

If you were trying to begin from a pretrained model and generalize to new images, it could definitely introduce some error, as the new images are not only in a new setting than the model was trained with, but the camera may indeed be different. I'd still probably start with the intrinsics the same as the pretrained model uses, and see how predictions look.

Hope that helps! Good luck :)
Chris

**Comment by leilai125** [comment]
Thanks for the nice replying! Currently I have several YouTube videos (they are recorded using different cameras with unknown intrinsic parameters). So maybe it's a bad idea to train on them? (because intrinsics that vary across images)
also a bad idea to use trained model to predict other new images that recorded by different unknown cameras? Does this indicate this model heavily rely on camera parameters? 

Thanks! Have a good day!

**Comment by crockwell** [comment]
Yeah, training and predicting with varying unknown intrinsics could be tricky. 

You make a good point - you could imagine a model that also fits intrinsics along with pose. Ours makes the assumption of known intrinsics, which is a limitation.

**Comment by rmadan2** [comment]
Hi, thank you for publishing the code. If I were to use a stereo pair with demo.py, how would I change the intrinsics? The intrinsics in demo.py are coded as such:
`if "matterport" in args.ckpt:
        intrinsics = np.stack([np.array([[517.97, 517.97, 320, 240], [517.97, 517.97, 320, 240]])]).astype(np.float32)
    else:
        intrinsics = np.stack([np.array([[128,128,128,128], [128,128,128,128]])]).astype(np.float32)`

I am assuming that you have stacked two vectors together containing intrinsic parameters for each camera of an image pair passed to the script.

**Comment by crockwell** [comment]
Hello -- the values are [fx,fy,cx,cy] for image 1 and image 2. I'd recommend using the matterport model as the "other" (streetlearn) model isn't trained to predict translation. Also, the matterport model isn't trained with varying intrinsics, so it may not be super robust to intrinsics other than the ones used with matterport during training. I think these days, [DUSt3R](https://github.com/naver/dust3r) should be more robust for this situation.

**Comment by rmadan2** [comment]
Thank you for the speedy response!
