### ISSUE TITLE
EMM’s ∼ U⊤U is valid only when `self.cross_features` = True ?

### ISSUE THREAD

**Issue by ash-aldujaili** [crockwell/rel_pose#2]
Enjoyed reading your paper. Nice work!

Nevertheless, I had a doubt as I went through the code and noticed the hyper parameter `cross_features` which I think governs equation 2's V_i, whether it is V_i.T A V_i or V_j.T A V_i. It looks to me when `self.cross_features` is False, the Essential Matrix module does not really capture the matrix U⊤U. Correct? If so, why would `self.cross_features`=False still be helpful?

Thank you.

**Comment by crockwell** [comment]
Hi Abdullah,

Good questions! Indeed, we use self.cross_features = False, meaning "V" is the same on both sides of the bilinear attention. If you look at the equation 2 in the paper, as well as figure 2, you'll see the same "V" is used on both sides of bilinear-attention. 

Do we really capture UTU if cross_features=False? The answer is yes. Supplemental section E shows mathematically PhiT @ A @ Phi produces ~UTU; where Phi is a set of positional encodings appended to V. So actually, as long as we append positional encodings to V, we can produce ~UTU regardless of whether cross_features = False or True. 

Why do we choose cross_features = False? We actually tried cross_features = True in some early experiments, but found cross_features = False worked better. Here is some of our thinking as to why this happened: (1) ~UTU is calculated in both cases, so perhaps this is sufficient in terms of correspondences, so the rest of the matrix needs to produce good visual features and (2) it could be that visual features aren't passed through cross-attention as effectively. I think analyzing the details of this further could be interesting; to me the high-level takeaway is that image features + essential matrix-based correspondence is a strong and intuitive baseline.

Best,
Chris

**Comment by ash-aldujaili** [comment]
Thank you for the prompt response and clarification, Chris!

Agreed. If `self.no_pos_encoding` == False, then regardless of `cross_features`'s value, EMM’s ∼ U⊤U.
That said, I am trying to understand the rationale behind `visual features` sub-matrix of Eq 2 when `cross_features` = False:
For example, It looks like (according to Eq 9) visual features of patches I and J of image 1 are aggregated/combined if patch I of Image 1 and patch J of image 2 are correspondences, why would we want to do so. Am I making sense?

**Comment by crockwell** [comment]
Yeah I think I understand your point. So in equation 9 we refer to phi, which is the positional encodings appended to V, and corresponds to the positional ~UTU. So A (Q1 @ K2^T) will model correspondences between positions of image 1 (phi on left side of A) and positions of image 2 (phi on right side of A).

You're asking about the visual features. Most of the paper's equations do not refer to this.  In fact, as you point out, we aren't really computing correspondences in visual features. The reason this was empirically better in our early experiments I tried to explain in the last message, though I agree it feels more intuitive to compare visual features directly via cross-attention. If you get something to work, maybe it is a cool next paper? 😄

**Comment by ash-aldujaili** [comment]
Thank you, Chris.
Your answers cleared up my doubts. Again, very cool work! Looking forward to your next cool paper :)
