### ISSUE TITLE
Generating Epipolar lines

### ISSUE THREAD

**Issue by yashbhalgat** [crockwell/rel_pose#3]
Hi @crockwell, this is a really cool work!

I am trying to generate the epipolar lines given the relative pose predicted by your model. However, I am not able to obtain correct epipolar lines -- my hunch is that I have misunderstood either the coordinate system (X,Y,Z axes) convention used by the model or maybe the rotation matrix is transposed?

This is what I am getting with my own script (which obviously looks wrong):
![6ed97d8b-407d-40e4-9ba4-9f0fe90ab6cb](https://user-images.githubusercontent.com/8559512/199037434-ad0c1fac-f21e-412a-8fa8-abe179848e66.png)

I was wondering if you can share the script you used to generate the epipolar line figures in the paper? That would be immensely helpful!

Thanks,
Yash

**Comment by crockwell** [comment]
Thanks Yash!

Ah, yeah, generating this properly can be tricky :) I just uploaded some code I used for this [to the repo](https://github.com/crockwell/rel_pose/blob/main/generate_epipolar_imgs.py), let me know if you continue to have problems! 

Best,
Chris

**Comment by yashbhalgat** [comment]
Hi Chris, thanks very much!
Unfortunately, I am still having a problem. I am running your script using the demo Matterport images (same as the README). And I am using the **ground truth** relative pose as provided in the [demo.py](https://github.com/crockwell/rel_pose/blob/447353235e52ac8fda8d0ea0bfb42051237325bf/demo.py#L108) file.

I use this as the input in your provided script:
```
curr_path1 = "demo/matterport_1.png"
curr_path2 = "demo/matterport_2.png"
out_path1 = curr_path1[:-4] + "_epipolar.png"
out_path2 = curr_path2[:-4] + "_epipolar.png"

rel_pose = [ 2.73153,  0.25285,  -1.35598,  0.10905,  0.00000,  0.56102,  0.82059] # in format x,y,z,qx,qy,qz,qw
rel_pose = np.array(rel_pose) # x, y, z, qx, qy, qz, qw
```

But the output seems wrong. The epipole should appear in the right side of the second image, but it appears in the left. Also, the two green lines should be close to the sofa and the plant. Can you please check this and let me know if I am wrong?

![matterport_epipolar_stitched](https://user-images.githubusercontent.com/8559512/200193245-0940aefb-8170-4868-8783-f8e8b57605ff.png)

------------------------------------------------------
The [generate_epipolar_imgs.py](https://github.com/crockwell/rel_pose/blob/447353235e52ac8fda8d0ea0bfb42051237325bf/generate_epipolar_imgs.py#L15) says `quaternion: wxyz`. So, I also tried changing the order of the predicted quaternion, but that doesn't work either.

**Comment by yashbhalgat** [comment]
Hi @crockwell, sorry to bother again with the CVPR deadline looming ahead!
I was wondering if you had a chance to look at this. I would appreciate any help here! :) 

Thanks,
Yash

**Comment by crockwell** [comment]
Hey Yash,

No bother -- definitely understandable with the deadline coming up. 

I did verify the ground truth relative pose matched this image pair, so seems like the challenge is mapping this to the correct pose to be used for epipolar line calculation. 

Unfortunately, I also have CVPR to worry about and my initial attempts didn't easily map this. I should be able to get it to you but it would likely be after CVPR. Instead, let me share with you the following from which I hope you can find a solution:

1) More pose information is available for each pair in the cached_set_test.json file. The demo pair is pair index 301.
2) Matterport coordinate conventions are attached
<img width="1073" alt="image (9)" src="https://user-images.githubusercontent.com/8130706/200446197-5bb2da8d-0c29-464f-96eb-89d95fecaa05.png">
3) Code to convert points from local frame to global frame is here:
https://github.com/jinlinyi/SparsePlanes/blob/main/sparsePlane/sparseplane/utils/mesh_utils.py#L65

Best,
Chris

**Comment by yashbhalgat** [comment]
Thanks Chris for the prompt reply! And best of luck with CVPR. :))
I will try to work out a solution from your suggestions. And will let you know once I figure it out.

**Comment by yashbhalgat** [comment]
Hi Chris @crockwell, hope your CVPR submission went well!

I tried to debug this issue with the tips you mentioned, but unfortunately haven't succeeded in finding the right transformation yet. I was wondering if you have some time now to look into this. Since you already have the epipolar lines figures in your paper, I hope debugging this would be a bit easier for you that it was for me.

Please let me know. I would really appreciate your help here. :) 

Best,
Yash

**Comment by crockwell** [comment]
Thanks Yash for the comments. We privately discussed this and I am uploading revised code for generating epipolar lines.
