### ISSUE TITLE
7scenes dataset

### ISSUE THREAD

**Issue by HannahHaensen** [crockwell/rel_pose#5]
Was there a speicfic reason to not evalaute on 7scenes and the cambridge dataset as they are often used in related works?

**Comment by crockwell** [comment]
So to clarify, our task is wide-baseline relative pose estimation -- estimating the relative pose between two previously unseen images taken in a previously unseen environment. 
The 7Scenes and Cambridge datasets are typically used in localization tasks (absolute pose in previously seen environment). For this reason, we do not use these datasets -- and relative pose estimation baselines to which we compare typically also do not use them.

**Comment by HannahHaensen** [comment]
@crockwell yeah i see the task i was just wondering cause other papers adressing RPR for example train on scannet and evalaute on 7scenes or similar 

https://github.com/nianticlabs/map-free-reloc

**Comment by crockwell** [comment]
Cool, thanks for sharing! 

It seems that could be an interesting test of generalization, we would consider in future work. Note -- in Supp Table 9 we test generalizing between StreetLearn and InteriorNet, which are similar.
