### ISSUE TITLE
What is the input image size?

### ISSUE THREAD

**Issue by shubhamwagh** [crockwell/rel_pose#6]
On skimming through the code it looks like it is 384 x 384, but in the supplemental paper it mentions it is 256 x 256.

Can you please confirm the input image size?

**Comment by crockwell** [comment]
Hi Shubham -- indeed, it is 256x256. You can see this in the code here: https://github.com/crockwell/rel_pose/blob/main/src/model.py#L125

**Comment by shubhamwagh** [comment]
Hi Chris, thanks for the reply. If I understood it correctty: 
The input image is of size **256 x 256**, then the augmentation reshapes it to **384 x 512**  size? Since it looks like, it uses the default argument as seen [here](https://github.com/crockwell/rel_pose/blob/35d1352fea09c941cef59b5f153ef3483db10bb5/train.py#L123) and [here](https://github.com/crockwell/rel_pose/blob/main/src/data_readers/base.py#L20)

and then it is resized to 224 x 224 (internally by the model) for Resnets? 

Is that correct or am I missing something?

Apologies, I am just trying to understand the input size here.

**Comment by crockwell** [comment]
In the datasets we used, images were read at 480x640, resized to 384x512 for augmentation (following prior work; albeit it could be cleaner), and finally we use 224x224 for ResNet. I realize the supplemental is indeed incorrect, then -- 224 is the number we feed into the model. Thanks for pointing this out!
